server:
  port: 8888


spring:
  datasource:
    url: jdbc:mariadb://toytrip.cgjt0cckbucb.ap-northeast-2.rds.amazonaws.com/toy_trip
    username: toytrip
    password: zaq1234!
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true